      SUBROUTINE FRED.FIND.SOURCE.FILE.UD.SUB(source_id,source_file_name)
         source_file_name = ''
         OPEN 'VOC' TO F.VOC ELSE RETURN
         READ R.VOC FROM F.VOC,source_id THEN
            IF R.VOC<1> = 'C' THEN
               IF R.VOC<3> = '' THEN
                  source_file_name = FIELD(R.VOC<2>,'/',1)
               END ELSE
                  source_file_name = FIELD(R.VOC<3>,' ',1)
               END
            END
         END
         OPEN '','_MAP_' TO F.MAP ELSE RETURN
         READ R.MAP FROM F.MAP,source_id THEN
            source_file_name = FIELD(R.MAP<3>,' ',1)
            IF source_file_name[1,1] = '/' THEN
               last_slash = COUNT(source_file_name,'/')
               source_file_name = FIELD(source_file_name,'/',last_slash+1)
            END
            IF source_file_name[1,1] = '\' THEN
               last_slash = COUNT(source_file_name,'\')
               source_file_name = FIELD(source_file_name,'\',last_slash+1)
            END
         END
         RETURN
